### PR TITLE
Audio fix for cockpit and general hemtt cleanup

### PR DESCRIPTION
**Pull request by SoraBytes**
This fixes the low audio in a cockpit. I didn't do extensive testing but it works as-is. The fix is in the file fnc_playSoundVehicle.sqf at line [18](https://github.com/Sora012/AWESome/blob/143a03bea43c1eb3daf292f0572733748f39f199/addons/main/functions/fnc_playSoundVehicle.sqf#L18) which I used the BI Wiki for [playSound](https://community.bistudio.com/wiki/playSound) to determine a fix.
I'm unsure the difference between values "1" and "2" but both seem to work. I opted to use "1" in this fix. Where I believe it will muffle for external listeners, but I didn't test it as I had no one to assist.

I do believe that the audio volumes need to be adjusted based on this new fix as they seem rather loud now but I tested with "f16 gpws high volume" ingame. The additional changes are general cleanup, renaming for hemtt to build. Thats why there are changes to string tables and a file rename from WARNING to WARN due to hemtt complaining for a "WARNING" function when its actually a file name.

### CODE REVIEW

**Comment by mgkid3310** [comment]
I believe the XEH_PREP.sqf still has the .sqf extension while the postinit and preinit scripts includes XEH_PREP.hpp, does this not trigger a missing file error?

**Comment by Sora012** [comment]
Unless I made a mistake with the push into the fork by missing a file (which is why [8d12eff](https://github.com/mgkid3310/AWESome/pull/68/commits/8d12eff1db75dda2d9f08c8ee63d2f2312c73e57) exists) I was able to build the addon and play just fine with no issues, I will double check by pulling my own fork and building again to verify it builds fine. Also after double checking the audio ealier I was right with the audio being vastly louder than the game now.

**Comment by Sora012** [comment]
Thats totally my bad with that, it built and worked because they existed locally, but didn't add them to the actual repo. Sorry about that.

**Review by mgkid3310 — APPROVED** [review]
LGTM!

**Comment by mgkid3310** [comment]
Looks good on my local test, will merge and publish as v1.4.19.1, thanks for the contribution!

**Pull request merged**
