### PR TITLE
WIP use KIAS and KPH

### PR DESCRIPTION
**Pull request by synixebrett**

### CODE REVIEW

**Comment by mgkid3310** [comment]
Thanks for the PR. Seems like a nice proposal, but just a few changes are required, After that it should be updated along v1.1.3
If you give me a nickname and e-mail I'll add those to README.md

**Comment by mgkid3310** [comment]
BTW did you check this code in-game? The line may exceed the table cell's horizontal size. If so making an option to choose KIAS or KPH would be great.

**Comment by synixebrett** [comment]
I plan on doing an option to pick between KIAS, KPH, and both. My and another guy from my group used this code the other day and everything went fine, but I haven't done a proper test build yet.

**Comment by synixebrett** [comment]
If `params` gets anything that isn't an array it converts it to a single element array. I can do the work on a CBA option for this PR. I should have added WIP to it.

**Comment by mgkid3310** [comment]
Well still, passing just the number not array seems wired to me... It would be nice if parameter is passed as array. Once the CBA options are done I'll process this PR at once.

**Pull request closed without merging**
