### PR TITLE
CBA Structure

### PR DESCRIPTION
**Pull request by synixebrett**
**What does this PR do?**
- Use CBA event handlers for XEH_preInit, XEH_preStart, XEH_postInit
- Use GVAR and FUNC. Inside addons/atc `orbis_atc_myVariable` is now `GVAR(myVariable)`

**Notice to other developers**
None of the code has really been changed, after going through the preprocessor the code will be almost the exact same. This just makes it easier for developers to work on the mod.

**Additional context**
I keep wanting to work on AWESome, but I spend more time figuring out how you are doing things compared to the time the feature would take to write. I have tried to change as little as possible to switch to the CBA structure.

GitHub makes it look like a lot changed. If that is a concern I would suggest actually cloning this PR locally and browsing around. You'll see it is mostly the same as it previously was.

### CODE REVIEW

**Comment by mgkid3310** [comment]
Is the changes in this PR tested? If so, I'll bring pull this PR on 1.1.9 update

**Comment by synixebrett** [comment]
GPWS, Checklists, ATIS are all tested. No errors from anything else but it needs a full test. The script I wrote to convert it all made a few errors that I caught but it is possible I missed one somewhere. I can give it a more scrutinized look if you're going to pull this PR.

**Comment by mgkid3310** [comment]
I've got my final exam coming next week so it might be late for me to test all the features. If the changes have no errors on your side, I'll first merge this PR and dev_1.1.9 then make last fixes.

**Comment by mgkid3310** [comment]
Oh and don't forget to leave your ID and e-mail on README.md

**Comment by synixebrett** [comment]
Um, https://www.youtube.com/watch?v=-Gh1lTcwdGY ?

**Comment by mgkid3310** [comment]
All major bugfixes are already on steam workshop, so there's no need for hurry for at least a few weeks. Thanks for all your work! 😃

**Comment by mgkid3310** [comment]
BTW is there a macro for packing pbos with pboprefix? I'm trying but getting "Include file z\orbis\addons\main\script_mod.hpp not found." error

`"C:\Program Files (x86)\Steam\steamapps\common\Arma 3 Tools\AddonBuilder\AddonBuilder.exe" "C:\Users\mgkid\Documents\GitHub\AWESome\addons\main" "C:\Users\mgkid\Downloads" -clear -prefix="z\orbis\addons\main" -project="C:\Users\mgkid\Documents\GitHub\AWESome" -sign="C:\Users\mgkid\Downloads\Personal\ARMA\Modding\[bikey]\Orbis2358_AWESome.biprivatekey" -binarize="C:\Program Files (x86)\Steam\steamapps\common\Arma 3 Tools\Binarize\binarize.exe"`

**Comment by synixebrett** [comment]
I was going to ask you about that on slack before you merged 😄.

This was built using HEMTT. https://synixebrett.github.io/HEMTT/#/

https://github.com/synixebrett/HEMTT/releases/tag/v0.6.1 you can download https://github.com/synixebrett/HEMTT/releases/download/v0.6.1/hemtt-v0.6.1-x86_64-pc-windows-msvc.zip and simply run `hemtt build` in the command line from the project directory.

**Comment by mgkid3310** [comment]
Wow I was living in ancient days until this day lol XD

**Pull request merged**
